#!/usr/bin/env bash
# =============================================================================
# MakeNashville Booking System — Nginx + SSL Setup
# =============================================================================
# Run this after you've configured your domain names in the admin dashboard
# (Admin → Settings → Server). It reads the configured URLs from the database,
# generates proper Nginx vhosts, and optionally provisions SSL via Certbot.
#
# Usage:
#   sudo scripts/setup-nginx.sh
# =============================================================================

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'
BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[info]${RESET}  $*"; }
success() { echo -e "${GREEN}[ok]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[warn]${RESET}  $*"; }
die()     { echo -e "${RED}[error]${RESET} $*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Please run as root: sudo $0"

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

[[ -f .env ]] || die ".env not found. Run scripts/install.sh first."
set -a; source .env; set +a

# ── Read domain settings from the DB ──────────────────────────────────────────
info "Reading domain settings from database..."

read_setting() {
  local key="$1"
  psql "$DATABASE_URL" -tAq \
    -c "SELECT value FROM system_settings WHERE key='${key}';" 2>/dev/null || true
}

API_URL="$(read_setting API_PUBLIC_URL)"
WEB_URL="$(read_setting WEB_PUBLIC_URL)"
KIOSK_URL="$(read_setting KIOSK_PUBLIC_URL)"

# Fall back to .env values if not set in DB
API_URL="${API_URL:-${API_PUBLIC_URL:-}}"
WEB_URL="${WEB_URL:-${WEB_PUBLIC_URL:-}}"
KIOSK_URL="${KIOSK_URL:-${KIOSK_PUBLIC_URL:-}}"

# Strip protocol and trailing slashes to get bare hostnames
strip_host() { echo "$1" | sed -E 's|https?://||;s|/.*$||'; }

API_HOST="$(strip_host "$API_URL")"
WEB_HOST="$(strip_host "$WEB_URL")"
KIOSK_HOST="$(strip_host "$KIOSK_URL")"

# STATUS_DOMAIN isn't a named setting yet — prompt for it
read -rp "$(echo -e "${CYAN}Status screen domain${RESET} (e.g. status.yourdomain.com): ")" STATUS_HOST
STATUS_HOST="${STATUS_HOST:-}"

[[ -n "$API_HOST" ]]    || die "API_PUBLIC_URL is not configured. Set it in Admin → Settings → Server first."
[[ -n "$WEB_HOST" ]]    || die "WEB_PUBLIC_URL is not configured. Set it in Admin → Settings → Server first."
[[ -n "$KIOSK_HOST" ]]  || die "KIOSK_PUBLIC_URL is not configured. Set it in Admin → Settings → Server first."
[[ -n "$STATUS_HOST" ]] || die "Status screen domain cannot be empty."

echo
info "Configuring Nginx for:"
echo "    API            → $API_HOST"
echo "    Member portal  → $WEB_HOST"
echo "    Kiosk          → $KIOSK_HOST"
echo "    Status screen  → $STATUS_HOST"
echo

# ── Write Nginx config ────────────────────────────────────────────────────────

cat > /etc/nginx/sites-available/mnbooking <<NGINX
# MakeNashville Booking System — generated by setup-nginx.sh

# API
server {
    listen 80;
    server_name ${API_HOST};
    location / {
        proxy_pass         http://127.0.0.1:4000;
        proxy_http_version 1.1;
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
    }
}

# Member portal
server {
    listen 80;
    server_name ${WEB_HOST};
    root ${REPO_DIR}/apps/web/dist;
    index index.html;
    location / { try_files \$uri \$uri/ /index.html; }
}

# Kiosk
server {
    listen 80;
    server_name ${KIOSK_HOST};
    root ${REPO_DIR}/apps/kiosk/dist;
    index index.html;
    location / { try_files \$uri \$uri/ /index.html; }
}

# Status screen
server {
    listen 80;
    server_name ${STATUS_HOST};
    root ${REPO_DIR}/apps/status/dist;
    index index.html;
    location / { try_files \$uri \$uri/ /index.html; }
}
NGINX

rm -f /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/mnbooking /etc/nginx/sites-enabled/mnbooking
nginx -t && systemctl reload nginx
success "Nginx vhosts configured."

# ── SSL via Certbot ───────────────────────────────────────────────────────────
echo
read -rp "$(echo -e "${CYAN}Provision SSL certificates with Certbot? [y/N]${RESET}: ")" want_ssl
if [[ "${want_ssl,,}" == "y" ]]; then
  read -rp "$(echo -e "${CYAN}Email for Let's Encrypt notifications${RESET}: ")" SSL_EMAIL
  [[ -n "$SSL_EMAIL" ]] || die "Email is required for Certbot."

  certbot --nginx \
    -d "$API_HOST" \
    -d "$WEB_HOST" \
    -d "$KIOSK_HOST" \
    -d "$STATUS_HOST" \
    --non-interactive \
    --agree-tos \
    --email "$SSL_EMAIL" \
    --redirect

  success "SSL certificates provisioned."
  echo
  info "Update your URLs in Admin → Settings → Server to use https://"
  echo "    API_PUBLIC_URL   = https://${API_HOST}"
  echo "    WEB_PUBLIC_URL   = https://${WEB_HOST}"
  echo "    KIOSK_PUBLIC_URL = https://${KIOSK_HOST}"
  echo
  warn "Then restart the API: pm2 restart mn-api"
else
  warn "SSL skipped. Re-run this script and choose 'y' when ready."
fi
